# Generated by Django 6.0.3 on 2026-04-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text="Patient's reported symptoms")),
                ('diagnosis', models.TextField(help_text="Doctor's official diagnosis")),
                ('prescription', models.TextField(blank=True, help_text='Prescribed medications and dosage')),
                ('notes', models.TextField(blank=True, help_text='Additional doctor notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='appointments.appointment')),
            ],
        ),
    ]
